CREATE TABLE evento (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    titulo VARCHAR(1000) NOT NULL,
    minimoValor DOUBLE NOT NULL,
    dataInscricao TIMESTAMP NOT NULL,
    sorteio TIMESTAMP NOT NULL
)

CREATE TABLE participante (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    nome VARCHAR(1000) NOT NULL,
    email VARCHAR(1000) NOT NULL,
    senha VARCHAR(10)
)